### ISSUE TITLE
gpbackup build failing with version=1.15.0+dev.39.gc8ab236

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpbackup#326]
When building gpbackup the process fails with error '**warning: pattern "all" matched no module dependencies**' when running "make depend" using Ubuntu 16.0.4

I have built gpbackup many times successfully in the past, the last time though was on 1st Nov with version=1.15.0+dev.3.gffbfe2a so some change to the Makefile since that date seems to have caused this error

Is there a way to specify the gpbackup version when installing so that I can continue to use the previous gpbackup version ?

**Comment by baileygm** [comment]
The installation process seems to be dependant on the go version being used so it would be worth putting the version used during development and testing in the README

I was using go 1.12.7 which did not work but it seems to install OK now with 1.13.4

**Comment by kyeap-pivotal** [comment]
Hi Bailey!

Thanks for opening up an issue and bringing this to our attention!

The makefile has indeed changed recently because we switched our project dependency manager to use go modules (changed from using dep). This was changed about 10 days ago. 

It looks like the issue that manifested here was that go did not know the project uses go modules. By default in go 1.12 and 1.13 the GO111MODULE environment variable is set to auto The value of this changes if the project directory is in $GOPATH/src or not. I found there was a small update to the behavior of this environment variable in the go1.13 release notes.

> The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src.

 This is why the update to go1.13 fixed the error encountered in the first post. To make the project compile correctly while being located in $GOPATH/src and with version of go older than 1.13 we can explicitly set `GO111MODULE=on` before downloading dependencies.

**Comment by kyeap-pivotal** [comment]
Issue fixed in with the latest commit 8e29577.

**Comment by baileygm** [comment]
Hi Kevin
I just tried the build again with your latest commit and Go version 1.12.7 and it still fails with the message "warning: pattern "all" matched no module dependencies".

I switched back to Go version 1.13.4 and all works fine so I have no real issue to address but other users may have problems still if using the older versions of Go

**Comment by baileygm** [comment]
Hi Kevin
I verified that your fix worked fine but found the same issue with gpbackup-s3-plugin so have created an issue for it - https://github.com/greenplum-db/gpbackup-s3-plugin/issues/11
